
# Mail Gmail (conferma prenotazioni)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luigichiarettione@gmail.com
spring.mail.password=vuin pvpx iynn dzyg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
# --- Configurazione Supabase PostgreSQL ---
# spring.datasource.url=jdbc:postgresql://db.ijckghwssyjhztzapdqz.supabase.co:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=Rexton070qwer!
# spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione per ambiente locale con Session Pooler Supabase
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ijckghwssyjhztzapdqz
spring.datasource.password=Rexton070qwer!
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080

# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
